---
title: "Governance Analysis"
author: "Larissa Neilson"
date: "5/19/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(broom)
library(ordinal)
library(MASS)
library(ggeffects)
library(effects)
library(forcats)
library(gtsummary)
library(brant)
library(kableExtra)
```

### Our predictors of governance

- Country
- Governance in law
- Governance in practice
- Who's responsible for enforcement (HHS Q)
- Perceived fish catch
- Food security

### Outcome

#### Four fisher archetypes:

- Committed
- Supportive
- Ambivalent
- Resistant

```{r, echo = FALSE, results = FALSE, message = FALSE}
# Read in the data
hhs_all_complete <- read_csv("hhs_all_complete.csv")
scaled_km_df <- read_csv("scaled_km_df.csv") %>%
  mutate(cluster_no = recode_factor(cluster_no,
                                    "Wavering" = "Ambivalent")) %>%
  mutate(cluster_no = fct_relevel(cluster_no,
                                  "Resistant",
                                  "Ambivalent",
                                  "Supportive",
                                  "Committed")) 
staff_survey <- read_csv("staff_survey.csv")
```


```{r}
# Join staff survey data with HHS data
gov_data <- inner_join(scaled_km_df, staff_survey, by = "ma_name")

gov_data <- gov_data %>%
  dplyr::select(ma_name, gov_law, gov_practice, country, x6_gender, x19_current_fish_catch, x49_enforcement_responsible, x54_food_availability, cluster_no)

# Clean data
gov_data <- gov_data %>% 
  mutate(x49_enforcement_responsible = na_if(x49_enforcement_responsible, "na")) %>%
  mutate(x49_enforcement_responsible = recode_factor(x49_enforcement_responsible,
                                                     "National Government,Subnational Government" = "Subnational Government",
                                                     "There is no enforcement system" = "No enforcement system",
                                                     "Subnational Government,Myself" = "Subnational Government",
                                                     "Myself,Subnational Government" = "Subnational Government",
                                                     "National Government, No enforcement system" = "National Government",
                                                     "Subnational Government,Fisheries Management Body" = "Fisheries Management Body",
                                                     "Fisheries Management Body,Subnational Government" = "Fisheries Management Body",
                                                     "Myself,Fisheries Management Body" = "Fisheries Management Body",
                                                     "Fisheries Management Body,No enforcement system" = "Fisheries Management Body",
                                                     "Myself,Subnational Government,National Government" = "Subnational Government",
                                                     "National Government,Fisheries Management Body" = "Fisheries Management Body",
                                                     "Myself,No enforcement system" = "Myself",
                                                     "Subnational Government,National Government,Myself" = "Subnational Government",
                                                     "No enforcement system,Myself" = "Myself",
                                                     "National Government,No enforcement system" = "No enforcement system",
                                                     "Subnational Government,Myself,Fisheries Management Body" = "Fisheries Management Body",
                                                     "No enforcement system,Subnational Government" = "Subnational Government")) %>% 
  drop_na()

# write.csv(gov_data, file = "gov_data.csv")
```

We will use Ordinal Logistic Regression

```{r}
# Get the data ready for OLR
# Convert to factors
gov_data$gov_law <- as.factor(gov_data$gov_law)
gov_data$gov_practice <- as.factor(gov_data$gov_practice)
gov_data$country <- as.factor(gov_data$country)
gov_data$x54_food_availability <- as.factor(gov_data$x54_food_availability)
gov_data$x19_current_fish_catch <- as.factor(gov_data$x19_current_fish_catch)

# Update ref level
gov_data$gov_law <- relevel(gov_data$gov_law, ref = "True co-management")
gov_data$gov_practice <- relevel(gov_data$gov_practice, ref = "True co-management")
gov_data$country <- relevel(gov_data$country, ref = "PHL")
gov_data$x49_enforcement_responsible <- relevel(gov_data$x49_enforcement_responsible, ref = "Fisheries Management Body")
gov_data$x54_food_availability <- relevel(gov_data$x54_food_availability, ref = "OK")
gov_data$x19_current_fish_catch <- relevel(gov_data$x19_current_fish_catch, ref = "Stayed the same")

str(gov_data)
summary(gov_data)

# Chi-square tests for independence
chi2 <- chisq.test(gov_data$cluster_no, gov_data$country, correct=F)
c(chi2$statistic, chi2$p.value)
print(chi2)

chi2 <- chisq.test(gov_data$gov_law, gov_data$country, correct=F)
print(chi2)

chi2 <- chisq.test(gov_data$gov_practice, gov_data$country, correct=F)
print(chi2)

chi2 <- chisq.test(gov_data$x54_food_availability, gov_data$country, correct=F)
print(chi2)

gov_data_sum <- gov_data %>% 
  filter(x19_current_fish_catch == "Improved heavily") %>% 
  count(cluster_no)

gov_data_sum %>%
  kbl() %>%
  kable_styling()
```


```{r, include = FALSE}
# Perform OLR + data viz
# JUST with governance in law and in practice first
gov_data_olr <- clm(cluster_no ~ gov_law + gov_practice, data = gov_data, link = "logit")
summary(gov_data_olr)

confint(gov_data_olr)
exp(coef(gov_data_olr))
exp(confint(gov_data_olr))
#exp(cbind(OR = coef(gov_data_olr), ci))

# Run model including enforcement responsibility
gov_data_olr <- clm(cluster_no ~ gov_law + gov_practice + x49_enforcement_responsible, data = gov_data, link = "logit")
summary(gov_data_olr)

confint(gov_data_olr)
exp(coef(gov_data_olr))
exp(confint(gov_data_olr))
#exp(cbind(OR = coef(m), ci))

# Run model including other possible predictors (country, enforcement, food availability)
gov_data_olr <- clm(cluster_no ~ gov_law + gov_practice + x49_enforcement_responsible + x54_food_availability, data = gov_data, link = "logit")

#x19_current_fish_catch, x49_enforcement_responsible, x54_food_availability

summary(gov_data_olr)
confint(gov_data_olr)
exp(coef(gov_data_olr))
exp(confint(gov_data_olr))
```


```{r}
# Use polr to conduct OLR
# Governance, country, fish catch
gov_ols <- polr(cluster_no ~ gov_law + gov_practice + x19_current_fish_catch, data = gov_data, Hess = TRUE)
summary(gov_ols)

brant(gov_ols)

summary <- coef(summary(gov_ols))
p <- pnorm(abs(summary[, "t value"]), lower.tail = FALSE) * 2
summary <- cbind(summary, "p value" = p)
summary

ci <- confint(gov_ols)
confint.default(gov_ols)
exp(coef(gov_ols))
exp(cbind(OR = coef(gov_ols), ci))

tbl_regression(gov_ols, exponentiate = TRUE)
```


```{r}
# Governance, country, enforcement
gov_ols <- polr(cluster_no ~ gov_law + gov_practice + x49_enforcement_responsible, data = gov_data, Hess = TRUE)
summary(gov_ols)

brant(gov_ols)

summary <- coef(summary(gov_ols))
p <- pnorm(abs(summary[, "t value"]), lower.tail = FALSE) * 2
summary <- cbind(summary, "p value" = p)
summary

ci <- confint(gov_ols)
confint.default(gov_ols)
exp(coef(gov_ols))
exp(cbind(OR = coef(gov_ols), ci))

tbl_regression(gov_ols, exponentiate = TRUE)
```

```{r}
# Governance, country, food availability
gov_ols <- polr(cluster_no ~ gov_law + gov_practice + x54_food_availability, data = gov_data, Hess = TRUE)
summary(gov_ols)

brant(gov_ols)

summary <- coef(summary(gov_ols))
p <- pnorm(abs(summary[, "t value"]), lower.tail = FALSE) * 2
summary <- cbind(summary, "p value" = p)
summary

ci <- confint(gov_ols)
confint.default(gov_ols)
exp(coef(gov_ols))
exp(cbind(OR = coef(gov_ols), ci))

tbl_regression(gov_ols, exponentiate = TRUE)
```

```{r}
# All variables
gov_ols <- polr(cluster_no ~ gov_law + gov_practice + x19_current_fish_catch + x49_enforcement_responsible + x54_food_availability, data = gov_data, Hess = TRUE)
summary(gov_ols)

brant(gov_ols)

summary <- coef(summary(gov_ols))
p <- pnorm(abs(summary[, "t value"]), lower.tail = FALSE) * 2
summary <- cbind(summary, "p value" = p)
summary

ci <- confint(gov_ols)
confint.default(gov_ols)
exp(coef(gov_ols))
exp(cbind(OR = coef(gov_ols), ci))

tbl_regression(gov_ols, exponentiate = TRUE)
```

```{r}
# All variables with country
gov_ols <- polr(cluster_no ~ gov_law + country + gov_practice + x19_current_fish_catch + x49_enforcement_responsible + x54_food_availability, data = gov_data, Hess = TRUE)
summary(gov_ols)

brant(gov_ols)

summary <- coef(summary(gov_ols))
p <- pnorm(abs(summary[, "t value"]), lower.tail = FALSE) * 2
summary <- cbind(summary, "p value" = p)
summary

ci <- confint(gov_ols)
confint.default(gov_ols)
exp(coef(gov_ols))
exp(cbind(OR = coef(gov_ols), ci))

tbl_regression(gov_ols, exponentiate = TRUE)
```



















