---
title: "MAA Groupings"
author: "Larissa Neilson"
date: "2/1/2022"
output:
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(plotly)
library(kableExtra)
library(stargazer)
library(gridExtra)
library(patchwork)
library(viridis)
```

```{r, include = FALSE}
hhs_all_complete <- read_csv("hhs_all_complete.csv")
scaled_sum <- read_csv("scaled_sum.csv")
scaled_km_df <- read_csv("scaled_km_df.csv") %>%
  mutate(cluster_no = recode_factor(cluster_no,
                                    "Wavering" = "Ambivalent")) %>%
  mutate(x19_current_fish_catch = fct_relevel(x19_current_fish_catch,
                                              "Improved heavily",
                                              "Improved slightly",
                                              "Stayed the same",
                                              "Declined slightly",
                                              "Declined a lot")) %>% 
  mutate(x49_enforcement_responsible = fct_relevel(x49_enforcement_responsible,
                                              "Fisheries Management Body",
                                              "No enforcement system",
                                              "Myself",
                                              "Subnational Government",
                                              "National Government")) %>%
  mutate(cluster_no = fct_relevel(cluster_no,
                                  "Committed",
                                  "Supportive",
                                  "Ambivalent",
                                  "Resistant"))

# Clean Honduras data
clean_gov_data <- scaled_km_df %>%
  mutate(x49_enforcement_responsible = recode_factor(x49_enforcement_responsible,
                                                     "National Government,Subnational Government" = "Subnational Government",
                                                     "There is no enforcement system" = "No enforcement system",
                                                     "Subnational Government,Myself" = "Subnational Government",
                                                     "Myself,Subnational Government" = "Subnational Government",
                                                     "National Government, No enforcement system" = "National Government",
                                                     "Subnational Government,Fisheries Management Body" = "Fisheries Management Body",
                                                     "Fisheries Management Body,Subnational Government" = "Fisheries Management Body",
                                                     "Myself,Fisheries Management Body" = "Fisheries Management Body",
                                                     "Fisheries Management Body,No enforcement system" = "Fisheries Management Body",
                                                     "Myself,Subnational Government,National Government" = "Subnational Government",
                                                     "National Government,Fisheries Management Body" = "Fisheries Management Body",
                                                     "Myself,No enforcement system" = "Myself",
                                                     "Subnational Government,National Government,Myself" = "Subnational Government",
                                                     "No enforcement system,Myself" = "Myself",
                                                     "National Government,No enforcement system" = "No enforcement system",
                                                     "Subnational Government,Myself,Fisheries Management Body" = "Fisheries Management Body",
                                                     "No enforcement system,Subnational Government" = "Subnational Government")) %>%
  mutate(x49_enforcement_responsible = fct_relevel(x49_enforcement_responsible,
                                              "Fisheries Management Body",
                                              "No enforcement system",
                                              "Myself",
                                              "Subnational Government",
                                              "National Government"))
```

```{r, include = FALSE}
# All
x19_by_ma <- clean_gov_data %>% 
  select(x19_current_fish_catch, cluster_no, ma_name, country) %>% 
  group_by(ma_name, country) %>% 
  count(x19_current_fish_catch) %>% 
  drop_na()

x19_by_ma_counts <- x19_by_ma %>%
  group_by(ma_name, country) %>% 
  summarise(n = sum(n))

# Brazil
x19_by_ma_bra <- x19_by_ma %>% 
  filter(country == "BRA")

# Micronesia
x19_by_ma_fsm <- x19_by_ma %>% 
  filter(country == "FSM")

# Honduras
x19_by_ma_hnd <- x19_by_ma %>% 
  filter(country == "HND")

# Indonesia
x19_by_ma_idn <- x19_by_ma %>% 
  filter(country == "IDN")

# Mozambique
x19_by_ma_moz <- x19_by_ma %>% 
  filter(country == "MOZ")

# Philippines
x19_by_ma_phl <- x19_by_ma %>% 
  filter(country == "PHL")

# Palau
x19_by_ma_plw <- x19_by_ma %>% 
  filter(country == "PLW")

```

```{r, include = FALSE}
bra_catch <- ggplot(x19_by_ma_bra, aes(fill = x19_current_fish_catch, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip() +
  theme_light() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom", axis.text.y=element_blank(), axis.title.y = element_blank())

bra_catch

fsm_catch <- ggplot(x19_by_ma_fsm, aes(fill = x19_current_fish_catch, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip() +
  theme_light() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom", axis.text.y=element_blank(), axis.title.y = element_blank())

fsm_catch

hnd_catch <- ggplot(x19_by_ma_hnd, aes(fill = x19_current_fish_catch, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip() +
  theme_light() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom", axis.text.y=element_blank(), axis.title.y = element_blank())

hnd_catch

idn_catch <- ggplot(x19_by_ma_idn, aes(fill = x19_current_fish_catch, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip() +
  theme_light() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom", axis.text.y=element_blank(), axis.title.y = element_blank())

idn_catch

moz_catch <- ggplot(x19_by_ma_moz, aes(fill = x19_current_fish_catch, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip() +
  theme_light() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom", axis.text.y=element_blank(), axis.title.y = element_blank())

moz_catch

phl_catch <- ggplot(x19_by_ma_phl, aes(fill = x19_current_fish_catch, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip() +
  theme_light() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom", axis.text.y=element_blank(), axis.title.y = element_blank())

phl_catch

plw_catch <- ggplot(x19_by_ma_plw, aes(fill = x19_current_fish_catch, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip() +
  theme_light() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom", axis.text.y=element_blank(), axis.title.y = element_blank())

plw_catch
```

```{r, include = FALSE}
# All
x49_by_ma <- clean_gov_data %>% 
  select(x49_enforcement_responsible, cluster_no, ma_name, country) %>% 
  group_by(ma_name, country) %>% 
  count(x49_enforcement_responsible) %>% 
  drop_na()

# Brazil
x49_by_ma_bra <- x49_by_ma %>% 
  filter(country == "BRA")

# Micronesia
x49_by_ma_fsm <- x49_by_ma %>% 
  filter(country == "FSM")

# Honduras
x49_by_ma_hnd <- x49_by_ma %>% 
  filter(country == "HND")

# Indonesia
x49_by_ma_idn <- x49_by_ma %>% 
  filter(country == "IDN")

# Mozambique
x49_by_ma_moz <- x49_by_ma %>% 
  filter(country == "MOZ")

# Philippines
x49_by_ma_phl <- x49_by_ma %>% 
  filter(country == "PHL")

# Palau
x49_by_ma_plw <- x49_by_ma %>% 
  filter(country == "PLW")
```

```{r, include = FALSE}
bra_enf <- ggplot(x49_by_ma_bra, aes(fill = x49_enforcement_responsible, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip() +
  theme_light() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom", axis.text.y=element_blank(), axis.title.y = element_blank())

bra_enf

# Drop nas
fsm_enf <- ggplot(x49_by_ma_fsm, aes(fill = x49_enforcement_responsible, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip() +
  theme_light() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom", axis.text.y=element_blank(), axis.title.y = element_blank())

fsm_enf

#Honduras allowed more than one answer for Q 49
hnd_enf <- ggplot(x49_by_ma_hnd, aes(fill = x49_enforcement_responsible, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip() +
  theme_light() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom", axis.text.y=element_blank(), axis.title.y = element_blank())

hnd_enf

idn_enf <- ggplot(x49_by_ma_idn, aes(fill = x49_enforcement_responsible, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip() +
  theme_light() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom", axis.text.y=element_blank(), axis.title.y = element_blank())

idn_enf

moz_enf <- ggplot(x49_by_ma_moz, aes(fill = x49_enforcement_responsible, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip() +
  theme_light() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom", axis.text.y=element_blank(), axis.title.y = element_blank())

moz_enf

phl_enf <- ggplot(x49_by_ma_phl, aes(fill = x49_enforcement_responsible, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip() +
  theme_light() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom", axis.text.y=element_blank(), axis.title.y = element_blank())

phl_enf

plw_enf <- ggplot(x49_by_ma_plw, aes(fill = x49_enforcement_responsible, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip() +
  theme_light() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom", axis.text.y=element_blank(), axis.title.y = element_blank())

plw_enf
```

```{r, include = FALSE}
# All
cluster_by_ma <- clean_gov_data %>% 
  select(cluster_no, ma_name, country) %>% 
  group_by(ma_name, country) %>% 
  count(cluster_no) %>% 
  drop_na()

cluster_by_ma_counts <- cluster_by_ma %>%
  group_by(ma_name, country) %>% 
  summarise(n = sum(n))

# Brazil
cluster_by_ma_bra <- cluster_by_ma %>% 
  filter(country == "BRA") %>%
  filter(ma_name != "RESEX Maracanã") %>% 
  filter(ma_name != "RESEX Caeté-Taperaçu")

# Micronesia
cluster_by_ma_fsm <- cluster_by_ma %>% 
  filter(country == "FSM")

# Honduras
cluster_by_ma_hnd <- cluster_by_ma %>% 
  filter(country == "HND") %>% 
  filter(ma_name != "Santa Rosa de Aguan") %>% 
  filter(ma_name != "Roatan") %>% 
  filter(ma_name != "Iriona")

# Indonesia
cluster_by_ma_idn <- cluster_by_ma %>% 
  filter(country == "IDN")

# Mozambique
cluster_by_ma_moz <- cluster_by_ma %>% 
  filter(country == "MOZ") %>% 
  filter(ma_name != "Simuco")

# Philippines
cluster_by_ma_phl <- cluster_by_ma %>% 
  filter(country == "PHL")

# Palau
cluster_by_ma_plw <- cluster_by_ma %>% 
  filter(country == "PLW")
```

```{r, include = FALSE}
bra_clust <- ggplot(cluster_by_ma_bra, aes(fill = cluster_no, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  xlab(NULL) +
  ylab("n %") +
  coord_flip() +
  theme_minimal() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom")

bra_clust + labs(fill = "Fisher Archetype")


fsm_clust <- ggplot(cluster_by_ma_fsm, aes(fill = cluster_no, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip() +
  theme_light() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom")

fsm_clust

hnd_clust <- ggplot(cluster_by_ma_hnd, aes(fill = cluster_no, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  xlab(NULL) +
  ylab("n %") +
  coord_flip() +
  theme_minimal() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom")

hnd_clust + labs(fill = "Fisher Archetype")

idn_clust <- ggplot(cluster_by_ma_idn, aes(fill = cluster_no, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip() +
  theme_light() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom")

idn_clust

moz_clust <- ggplot(cluster_by_ma_moz, aes(fill = cluster_no, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  xlab(NULL) +
  ylab("n %") +
  coord_flip() +
  theme_minimal() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom")

moz_clust + labs(fill = "Fisher Archetype")

phl_clust <- ggplot(cluster_by_ma_phl, aes(fill = cluster_no, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip() +
  theme_light() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom")

phl_clust

plw_clust <- ggplot(cluster_by_ma_plw, aes(fill = cluster_no, y = n, x = ma_name)) +
  geom_bar(position = "fill", stat = "identity") +
  coord_flip() +
  theme_light() +
  scale_fill_viridis_d(option = "viridis") +
  theme(legend.direction = "vertical", legend.position = "bottom")

plw_clust
```

#### Brazil

```{r, echo = FALSE}
# Brazil
bra_clust + bra_enf

bra_clust + bra_catch
```

#### Micronesia

```{r, echo = FALSE}
# Micronesia
fsm_clust + fsm_enf

fsm_clust + fsm_catch
```

#### Honduras

```{r, echo = FALSE}
# Honduras
hnd_clust + hnd_enf

hnd_clust + hnd_catch
```

#### Indonesia

```{r, echo = FALSE}
# Indonesia
idn_clust + idn_enf

idn_clust + idn_catch
```

#### Mozambique

```{r, echo = FALSE}
# Mozambique
moz_clust + moz_enf

moz_clust + moz_catch
```

#### Philippines

```{r, echo = FALSE}
# Philippines
phl_clust + phl_enf

phl_clust + phl_catch
```

#### Palau

```{r, echo = FALSE}
# Palau
plw_clust + plw_enf

plw_clust + plw_catch
```


```{r}
# Final figures for country MAA visualizations - Brazil, Honduras, Mozambique
# Only the types x gov in law and gov in practice
# Exclude MAAs with n > 10


```
