---
output: 
html_document:
  theme: lumen
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
```


```{r, include = FALSE, echo = FALSE}
# Load packages
library(tidyverse)
library(janitor)
library(tidyr)
library(ggplot2)
library(kableExtra)
library(knitr)
library(naniar)
library(here)
library(dplyr)
library(scales)

```

<div align="center"> <font size="+3"> **Fish Forever - Summary of HHSs** </font> 

***

```{r, include = FALSE}
hhs_global <- read_csv("hhs_global.csv")
```


<div align="left"> <font size="+3"> **Engagement** </font>

```{r}
# Check out stats for engagement related questions

## Create subset of global with only engagement question columns

hhs_global_engagement <- hhs_global %>% 
  select(c(x44_meeting_attendance, x45_leadership_position, x48_enforcement_participation, x53_encourage_regulations, x61f_rights_distribution_fair, x61g_fishing_change_behavior))

  ## Create summary dataframe of engagement questions - % of surveys with question answered
engagement_sums <- colSums(is.na(hhs_global_engagement)) %>% 
  data.frame() %>% 
  rownames_to_column(var = "question") %>% 
  rename("number_of_nas" = 2) %>% 
  mutate(percentage_answered = percent(((15509-number_of_nas)/15509), accuracy = 1.0)) %>% 
  arrange(desc(percentage_answered)) %>% 
  slice(-20) %>% 
  select(1, 3) %>% 
  rename("Survey Question" = question) %>% 
  rename("% of surveys with question answered" = percentage_answered)

## Summary table
knitr::kable(engagement_sums, format = "html", caption = "Engagement Questions Breakdown") %>% 
  kable_styling(c("condensed", "responsive", "bordered"), full_width = F, position = "left") %>% 
  collapse_rows(columns = 1, valign = "middle")

```


***

<div align="left"> <font size="+3"> **Agreement** </font>

```{r}
# Check out stats for agreement related questions

## Create subset of global with only agreement question columns
hhs_global_agreement <- hhs_global %>% 
  select(c(x10_mpa_important, x43_ma_benefits, x43_ma_benefits_opinion, x46_represent_interests, x47_represent_contributions, x52_ma_benefit_5yrs, x53_encourage_regulations, x61a_current_regulations, x61e_violations_decrease_profit, x62_reserve_compliance, x64_wrong_fishing_reserve))

  ## Create summary dataframe of agreement questions - % of surveys with question answered
agreement_sums <- colSums(is.na(hhs_global_agreement)) %>% 
  data.frame() %>% 
  rownames_to_column(var = "question") %>% 
  rename("number_of_nas" = 2) %>% 
  mutate(percentage_answered = percent(((15509-number_of_nas)/15509), accuracy = 1.0)) %>% 
  arrange(desc(percentage_answered)) %>% 
  slice(-20) %>% 
  select(1, 3) %>% 
  rename("Survey Question" = question) %>% 
  rename("% of surveys with question answered" = percentage_answered)

## Summary table
knitr::kable(agreement_sums, format = "html", caption = "Agreement Questions Breakdown") %>% 
  kable_styling(c("condensed", "responsive", "bordered"), full_width = F, position = "left") %>% 
  collapse_rows(columns = 1, valign = "middle")

```

\newpage

***

<div align="left"> <font size="+3"> **Governance** </font>

Question 4 not in dataset - it was a filtering question and responses weren't recorded. 

```{r}
# Check out stats for agreement related questions

## Create subset of global with only agreement question columns
hhs_global_governance <- hhs_global %>% 
  select(c(x49_enforcement_responsible, x61c_community_participation))

  ## Create summary dataframe of agreement questions - % of surveys with question answered
governance_sums <- colSums(is.na(hhs_global_governance)) %>% 
  data.frame() %>% 
  rownames_to_column(var = "question") %>% 
  rename("number_of_nas" = 2) %>% 
  mutate(percentage_answered = percent(((15509-number_of_nas)/15509), accuracy = 1.0)) %>% 
  arrange(desc(percentage_answered)) %>% 
  slice(-20) %>% 
  select(1, 3) %>% 
  rename("Survey Question" = question) %>% 
  rename("% of surveys with question answered" = percentage_answered)

## Summary table
knitr::kable(governance_sums, format = "html", caption = "Governance Questions Breakdown") %>% 
  kable_styling(c("condensed", "responsive", "bordered"), full_width = F, position = "left") %>% 
  collapse_rows(columns = 1, valign = "middle")

```


***

<div align="left"> <font size="+3"> **Ecological Outcomes** </font>

```{r}
# Check out stats for agreement related questions

## Create subset of global with only agreement question columns
hhs_global_ecological <- hhs_global %>% 
  select(c(x19_current_fish_catch, x22_catch_5yrs, x23_job_secure))

  ## Create summary dataframe of agreement questions - % of surveys with question answered
ecological_sums <- colSums(is.na(hhs_global_ecological)) %>% 
  data.frame() %>% 
  rownames_to_column(var = "question") %>% 
  rename("number_of_nas" = 2) %>% 
  mutate(percentage_answered = percent(((15509-number_of_nas)/15509), accuracy = 1.0)) %>% 
  arrange(desc(percentage_answered)) %>% 
  slice(-20) %>% 
  select(1, 3) %>% 
  rename("Survey Question" = question) %>% 
  rename("% of surveys with question answered" = percentage_answered)

## Summary table
knitr::kable(ecological_sums, format = "html", caption = "Ecological Outcomes Questions Breakdown") %>% 
  kable_styling(c("condensed", "responsive", "bordered"), full_width = F, position = "left") %>% 
  collapse_rows(columns = 1, valign = "middle")

```


***

<div align="left"> <font size="+3"> **Extent of Compliance** </font>

```{r}
# Check out stats for agreement related questions

## Create subset of global with only agreement question columns
hhs_global_compliance <- hhs_global %>% 
  select(c(x51a_fishers_gear_not_permitted, x51b_fishers_reserves, x51c_fishers_ma_area, x51d_fishers_violate_fish_size, x51e_fishers_caught, x63_fishing_in_reserve, x63_times_fishing_reserve))

  ## Create summary dataframe of agreement questions - % of surveys with question answered
compliance_sums <- colSums(is.na(hhs_global_compliance)) %>% 
  data.frame() %>% 
  rownames_to_column(var = "question") %>% 
  rename("number_of_nas" = 2) %>% 
  mutate(percentage_answered = percent(((15509-number_of_nas)/15509), accuracy = 1.0)) %>% 
  arrange(desc(percentage_answered)) %>% 
  slice(-20) %>% 
  select(1, 3) %>% 
  rename("Survey Question" = question) %>% 
  rename("% of surveys with question answered" = percentage_answered)

## Summary table
knitr::kable(compliance_sums, format = "html", caption = "Extent of Compliance Questions Breakdown") %>% 
  kable_styling(c("condensed", "responsive", "bordered"), full_width = F, position = "left") %>% 
  collapse_rows(columns = 1, valign = "middle")

```

